name: Docs

on:
  push:
    paths: ["**.md"]
  pull_request:
    paths: ["**.md"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: DavidAnson/markdownlint-cli2-action@28e2f0411e6b77225ed55aa54b0e6750147bb8b0 # v19
        with:
          config: .markdownlint.json
          globs: "**.md"
